from typing import Protocol
from .domain import LifeEvent, Workflow, AuditEvent
class LifeEventRepository(Protocol):
 def add(self,event:LifeEvent)->None: ...
 def get(self,event_id:str)->LifeEvent|None: ...
class WorkflowRepository(Protocol):
 def add(self,workflow:Workflow)->None: ...
 def get(self,workflow_id:str)->Workflow|None: ...
 def by_event(self,event_id:str)->Workflow|None: ...
class AuditRepository(Protocol):
 def record(self,event:AuditEvent)->None: ...
class ConversationAIProvider(Protocol):
 def extract(self,text:str)->dict: ...
class SpeechToTextProvider(Protocol):
 def transcribe(self,audio:bytes)->str: ...
class TextToSpeechProvider(Protocol):
 def synthesize(self,text:str)->bytes: ...
class NotificationProvider(Protocol):
 def send(self,resident_id:str,message:str)->None: ...
class GovernmentServiceProvider(Protocol):
 def submit(self,service_id:str, task_id:str)->str: ...
